#!/usr/bin/env python3
# gen-cutout-capsule.py — build a capsule of garment cutouts for the dress-up
# figure, extracting each garment *off the model* with AI cloth segmentation.
#
# The 4F feed is mostly on-model (kid wearing the piece). rembg's
# "u2net_cloth_seg" model returns 3 masks per photo (0=upper, 1=lower, 2=full),
# so we lift just the upper garment for tops and the lower garment for bottoms.
# Footwear is flat-lay, so plain background removal (u2net) is enough.
#
#   source /tmp/werol-venv/bin/activate && python app/scripts/gen-cutout-capsule.py
#
# Outputs transparent PNGs → src/assets/cutouts/ + src/data/cutoutCapsule.ts.

import urllib.request, json, io, os, re
import numpy as np
from PIL import Image, ImageFilter
from rembg import remove, new_session

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
OUT_ASSETS = os.path.join(APP, "src/assets/cutouts")
OUT_DATA = os.path.join(APP, "src/data/cutoutCapsule.ts")

ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjcmNjYWdubmplc2xucG1mZGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNTAyMjAsImV4cCI6MjA5NDkyNjIyMH0.9k6gCQnr2dHuzMxiRcL9j3WTYmLsGOqB9elWU2S-5fI"
URL = "https://hcrccagnnjeslnpmfdky.supabase.co"

cloth = new_session("u2net_cloth_seg")
general = new_session("u2net")

# slot, categories, cloth-class (None ⇒ plain bg removal), how many to keep
PLAN = [
    ("top", ["tshirts", "hoodies", "jackets"], 0, 8),
    ("bottom", ["pants", "shorts"], 1, 8),
    ("feet", ["sneakers"], None, 6),
]

safe = lambda s: re.sub(r"[^a-zA-Z0-9]+", "_", s)


def fetch_json(path):
    req = urllib.request.Request(URL + path, headers={"apikey": ANON, "Authorization": "Bearer " + ANON})
    return json.load(urllib.request.urlopen(req, timeout=30))


def fetch_img(url):
    return Image.open(io.BytesIO(urllib.request.urlopen(url, timeout=30).read())).convert("RGB")


def open_close(alpha):
    m = Image.fromarray(alpha)
    m = m.filter(ImageFilter.MinFilter(3)).filter(ImageFilter.MaxFilter(5)).filter(ImageFilter.MinFilter(3))
    return np.array(m)


def extract(img, cls):
    if cls is None:
        out = remove(img, session=general, post_process_mask=True).convert("RGBA")
        alpha = np.array(out)[:, :, 3]
    else:
        masks = cloth.predict(img)
        m = masks[cls].convert("L").filter(ImageFilter.GaussianBlur(1.2))
        alpha = np.where(np.array(m) > 40, 255, 0).astype(np.uint8)
    alpha = open_close(alpha)
    return alpha


os.makedirs(OUT_ASSETS, exist_ok=True)
capsule = {}
for slot, cats, cls, want in PLAN:
    capsule[slot] = []
    inlist = ",".join('"%s"' % c for c in cats)
    rows = fetch_json(f"/rest/v1/products?select=id,brand,name,price_current,currency,image_url,category&category=in.({inlist})&limit=40")
    for p in rows:
        if len(capsule[slot]) >= want:
            break
        try:
            img = fetch_img(p["image_url"])
            alpha = extract(img, cls)
            cov = (alpha > 0).mean()
            if cov < 0.04 or cov > 0.72:
                print("skip(cov %.2f)" % cov, end=" ")
                continue
            rgba = np.dstack([np.array(img), alpha])
            out = Image.fromarray(rgba, "RGBA")
            ys, xs = np.where(alpha > 0)
            pad = 8
            out = out.crop((max(0, xs.min() - pad), max(0, ys.min() - pad),
                            min(out.width, xs.max() + pad), min(out.height, ys.max() + pad)))
            file = safe(p["id"]) + ".png"
            out.save(os.path.join(OUT_ASSETS, file))
            capsule[slot].append({"id": p["id"], "brand": p["brand"], "name": p["name"],
                                  "price": p["price_current"], "currency": p["currency"] or "EUR", "file": file})
            print(".", end="", flush=True)
        except Exception as e:
            print("x", end="", flush=True)
    print(f" {slot}: {len(capsule[slot])}")

ts = "// AUTO-GENERATED by scripts/gen-cutout-capsule.py — do not edit by hand.\n"
ts += "// Garment cutouts extracted off the model via AI cloth segmentation.\n"
ts += "import type { ImageSourcePropType } from 'react-native';\n\n"
ts += "export type CutoutPiece = {\n  id: string;\n  brand: string;\n  name: string;\n  price: number;\n  currency: string;\n  cutout: ImageSourcePropType;\n};\n\n"
ts += "export type CutoutSlot = 'top' | 'bottom' | 'feet';\n\n"
ts += "export const CUTOUT_CAPSULE: Record<CutoutSlot, CutoutPiece[]> = {\n"
for slot in capsule:
    ts += f"  {slot}: [\n"
    for it in capsule[slot]:
        ts += "    { id: %s, brand: %s, name: %s, price: %s, currency: %s, cutout: require('../assets/cutouts/%s') },\n" % (
            json.dumps(it["id"]), json.dumps(it["brand"]), json.dumps(it["name"]), it["price"], json.dumps(it["currency"]), it["file"])
    ts += "  ],\n"
ts += "};\n"
with open(OUT_DATA, "w") as f:
    f.write(ts)
print("wrote", OUT_DATA)
