// AUTO-GENERATED by scripts/gen-cutout-capsule.py — do not edit by hand.
// Garment cutouts extracted off the model via AI cloth segmentation.
import type { ImageSourcePropType } from 'react-native';

export type CutoutPiece = {
  id: string;
  brand: string;
  name: string;
  price: number;
  currency: string;
  cutout: ImageSourcePropType;
};

export type CutoutSlot = 'top' | 'bottom' | 'feet';

export const CUTOUT_CAPSULE: Record<CutoutSlot, CutoutPiece[]> = {
  top: [
    { id: "4f:4FJWMM00TTSHF1658-51S", brand: "4F", name: "Diev\u010densk\u00e9 tri\u010dko bez potla\u010de - fialov\u00e9", price: 7.5, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTSHF1658_51S.png') },
    { id: "4f:4FJWMM00TTSHM1627-36S", brand: "4F", name: "Chlap\u010densk\u00e9 tri\u010dko s potla\u010dou - kobaltovo modr\u00e9", price: 9.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTSHM1627_36S.png') },
    { id: "4f:4FJWMM00TTSHM1627-43S", brand: "4F", name: "Chlap\u010densk\u00e9 tri\u010dko s potla\u010dou - kaki", price: 9.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTSHM1627_43S.png') },
    { id: "4f:4FJWMM00TTSHM1626-31S", brand: "4F", name: "Chlap\u010densk\u00e9 tri\u010dko - tmavomodr\u00e9", price: 7.5, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTSHM1626_31S.png') },
    { id: "4f:4FJWMM00TTSHM1627-31S", brand: "4F", name: "Chlap\u010densk\u00e9 tri\u010dko s potla\u010dou - tmavomodr\u00e9", price: 9.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTSHM1627_31S.png') },
    { id: "4f:4FJWMM00TTSHM1627-10S", brand: "4F", name: "Chlap\u010densk\u00e9 tri\u010dko s potla\u010dou - biele", price: 9.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTSHM1627_10S.png') },
    { id: "4f:4FJWMM00TTSHM1626-25S", brand: "4F", name: "Chlap\u010densk\u00e9 tri\u010dko - \u0161ed\u00e9", price: 7.5, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTSHM1626_25S.png') },
    { id: "4f:4FJWMM00TTSHM1626-20S", brand: "4F", name: "Chlap\u010densk\u00e9 tri\u010dko - \u010dierne", price: 7.5, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTSHM1626_20S.png') },
  ],
  bottom: [
    { id: "4f:4FJMM00TTROF267-56S", brand: "4F", name: "Diev\u010densk\u00e9 tepl\u00e1kov\u00e9 nohavice typu jogger", price: 14.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJMM00TTROF267_56S.png') },
    { id: "4f:4FJWMM00TTIGF178-20S", brand: "4F", name: "Diev\u010densk\u00e9 pleten\u00e9 leg\u00edny - \u010dierne", price: 9.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTIGF178_20S.png') },
    { id: "4f:4FJWMM00TTIGF178-31S", brand: "4F", name: "Diev\u010densk\u00e9 pleten\u00e9 leg\u00edny - tmavomodr\u00e9", price: 9.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTIGF178_31S.png') },
    { id: "4f:4FJWMM00TTIGF178-51S", brand: "4F", name: "Diev\u010densk\u00e9 pleten\u00e9 leg\u00edny - fialov\u00e9", price: 9.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTIGF178_51S.png') },
    { id: "4f:4FJWMM00TTROM0810-70S", brand: "4F", name: "Chlap\u010densk\u00e9 tepl\u00e1kov\u00e9 nohavice typu jogger - oran\u017eov\u00e9", price: 12.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTROM0810_70S.png') },
    { id: "4f:4FJRMM00UBDSM110-46S", brand: "4F", name: "Chlap\u010densk\u00e9 pl\u00e1\u017eov\u00e9 board\u0161ortky - morsk\u00e9 zelen\u00e9", price: 12.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJRMM00UBDSM110_46S.png') },
    { id: "4f:4FJWMM00TTROF0828-56S", brand: "4F", name: "NOHAVICE", price: 17.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTROF0828_56S.png') },
    { id: "4f:4FJWMM00TTROF0828-83S", brand: "4F", name: "NOHAVICE", price: 14.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJWMM00TTROF0828_83S.png') },
  ],
  feet: [
    { id: "4f:4FMM00FFLIF045A-70S", brand: "4F", name: "D\u00e1mske \u0161\u013eapky", price: 14.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FMM00FFLIF045A_70S.png') },
    { id: "4f:4FJSS23FFLIF084-90S", brand: "4F", name: "Diev\u010densk\u00e9 \u017eabky", price: 12.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJSS23FFLIF084_90S.png') },
    { id: "4f:4FJSS23FFLIF084-91S", brand: "4F", name: "Diev\u010densk\u00e9 \u017eabky", price: 12.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FJSS23FFLIF084_91S.png') },
    { id: "4f:4FMM00FFLIF018-56S", brand: "4F", name: "D\u00e1mske \u017eabky", price: 7.5, currency: "EUR", cutout: require('../assets/cutouts/4f_4FMM00FFLIF018_56S.png') },
    { id: "4f:4FMM00FFLIF031A-83S", brand: "4F", name: "D\u00e1mske \u0161\u013eapky", price: 17.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FMM00FFLIF031A_83S.png') },
    { id: "4f:4FMM00FFLIM047A-62S", brand: "4F", name: "P\u00e1nske \u0161\u013eapky", price: 14.9, currency: "EUR", cutout: require('../assets/cutouts/4f_4FMM00FFLIM047A_62S.png') },
  ],
};
